### ISSUE TITLE
Add Font Size Change Option

### ISSUE THREAD

**Issue by DrakoPensulo** [hasherezade/pe-bear-releases#22]
On machines with large resolution (like MS Book 2) the default font size may be too tiny for some users. It would be helpful for them to have option to make fonts larger (including the menu bar),

**Comment by hasherezade** [comment]
Funny coincidence, today I started working exactly on this feature. It is already implemented for some elements, for example:

![feature](https://user-images.githubusercontent.com/3115348/97098618-155ce800-167f-11eb-8679-dbd96c2fa7d6.png)

I will allow for changing fonts for other elements too.

**Comment by hasherezade** [comment]
soon in PE-bear:

![pebear_fonts](https://user-images.githubusercontent.com/3115348/98627440-8dc8d780-2314-11eb-97a0-a63afbbb7111.png)

![changed_fonts](https://user-images.githubusercontent.com/3115348/98627500-b2bd4a80-2314-11eb-9ba7-07755f2c29f6.png)

![screen_pebear](https://user-images.githubusercontent.com/3115348/98627313-3a568980-2314-11eb-8130-260683d7a4b6.png)

**Comment by hasherezade** [comment]
please check the new build: https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.2

**Comment by DrakoPensulo** [comment]
Good job. Thanks for the update.

**Comment by hasherezade** [comment]
I am glad that you like. Do you have any other remarks regarding this feature? If not, feel free to close the issue.

**Comment by hasherezade** [comment]
An improved version https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.2.2

**Comment by DrakoPensulo** [comment]
There is a problem with fonts in the leftmost column in Disasm window. It looks like few top lines of letters are truncated. 
![p1](https://user-images.githubusercontent.com/29009016/100180235-596d2380-2e9d-11eb-97fd-1ffacd1e58d2.png)
![p2](https://user-images.githubusercontent.com/29009016/100180237-5a05ba00-2e9d-11eb-985f-6e195ae7f9f1.png)

**Comment by hasherezade** [comment]
Thank you for reporting. What exactly is the font/size/OS used? Does the problem occur with other fonts also?

**Comment by hasherezade** [comment]
I see that on your machine also the icons are not scaling properly, so those 2 problems are probably interrelated. It could be caused by some problems with how the Qt interacts with your platform - looks like it does not retrieve the font metrics properly. I will try to make a workaround for this, but first I need to know more details about your platform, in order to be able to reproduce it on my side. Or, if it is not possible to reproduce, I will need your cooperation in testing of the patches.

**Comment by DrakoPensulo** [comment]
My machine: MS Surface Book 2. Windows 10. I believe it is High DPI. The font used in Disasm window is Segoe UI (it seems it is the default font). Font size 19 (regular) and smaller. I tested few other fonts, the  problem is the same.

**Comment by hasherezade** [comment]
I cannot reproduce this error on any of my machines, and I don't have MS Surface Book 2 to test there. Are you available to help me in testing? I will be sending you new builds, and you just have to deploy them and see if they work fine, sometimes read some parameters and send me back. If you are agree, please send me an e-mail: hasherezade@pm.me

**Comment by hasherezade** [comment]
ok, I managed to prepare the environment where I can reproduce it, so I don't have to bother you about it for now. It is related with scaling on Windows 10.

![reproduced](https://user-images.githubusercontent.com/3115348/101202981-4fe87600-366a-11eb-9977-a9f477ead655.png)

I will just let you know once the fix is ready, so that we can test it together before the release.

**Comment by hasherezade** [comment]
please check the latest release: https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.2.3

**Comment by DrakoPensulo** [comment]
The new release 0.5.2.3 resolves the issue. Thank you..
