### ISSUE TITLE
Compile versions compatible with Windows XP

### ISSUE THREAD

**Issue by LordGarfio** [hasherezade/pe-bear-releases#26]
Hello Mr. hasherezade,

PE-Bear versions released up to v0.4.0.3 work fine on Windows XP Pro SP3 and from v0.5.0 until v0.5.2.2 it no longer works.

Hereby, Can you compile a release to Windows XP ?

Thanks you in advanced.

**Comment by hasherezade** [comment]
Hi! 
The reason why PEbear stopped working on Windows XP, is that it got switched from Qt4 to Qt5. Unfortunately, making Qt5 work on Windows XP is quite problematic (more about it [here](https://stackoverflow.com/questions/50255414/is-it-possible-to-run-a-qt-5-10-programm-on-xp) ) - and the latest version of Qt5 don't support Windows XP at all.
Since the support of Windows XP is officially dropped by Microsoft, and lesser and lesser people use this OS, I decided to drop the backward compatibility with XP as well.
However, I always try to come forward the needs of my users, so if there is an interest in supporting Windows XP, I will see what I can do about it.

**Comment by LordGarfio** [comment]
Okay hasherezade.

I hope the following information is useful for the cause:

How to build in Windows (XP) ?
 - Install Visual Studio 2013 (en_visual_studio_community_2013_with_update_5_x86_dvd_6816332.iso).
 - Install Qt 5.6.3 for VS2013 (qt-opensource-windows-x86-msvc2013-5.6.3.exe).

The information above has been taken from github.com/horsicq/Detect-It-Easy

Thanks you.

**Comment by hasherezade** [comment]
@LordGarfio - I added a legacy build to the recent release:

https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.3.2

**Comment by LordGarfio** [comment]
Thanks you, 

PE-bear x32 v0.5.3.2 Legacy works fine on Windows XP SP3 with POSReady 2009.
