### ISSUE TITLE
Adding the CLI/CLR Header under the DataDirectories node

### ISSUE THREAD

**Issue by ethanr0x** [hasherezade/pe-bear-releases#30]
Hi there,

it would be great if some .NET awareness could be added to already great tool.

**Comment by hasherezade** [comment]
Hi! Thank you for the suggestion! I am agree with you that .NET header parsing would be useful. It is already on my TODO but I will give it a higher priority.

**Comment by hasherezade** [comment]
Please check the latest release, this bug was fixed:
https://github.com/hasherezade/pe-bear-releases/releases/tag/0.5.3

![data_dir_entry](https://user-images.githubusercontent.com/3115348/104817581-74676e80-5822-11eb-9067-c1d64c2ab0a7.png)

In addition, I am planning to add parsing of the whole .NET header in the next release. It will be displayed on additional tab.

**Comment by ethanr0x** [comment]
Good job :)
