### ISSUE TITLE
Imports tab shows even if invalid

### ISSUE THREAD

**Issue by Shadlock0133** [hasherezade/pe-bear-releases#44]
PE-bear version: v0.5.5.3

I have an exe file with data directory size set to 0. This causes "Data Directory" view to be filled with garbage data (but it's not that important), and for some reason "Imports" tab is displayed, also filled with garbage.

Here is the file, compressed:
[main.zip](https://github.com/hasherezade/pe-bear-releases/files/8800595/main.zip)

**Comment by hasherezade** [comment]
hi!
in the example that you shared, the VA of Import Table is non-zero (`1`), and also the size(`1000`):

![size_filled](https://user-images.githubusercontent.com/3115348/171175910-0890e6d9-f826-4e15-91ee-9471ef006f6f.png)

![garbage_table](https://user-images.githubusercontent.com/3115348/171177007-0aee7275-cebe-47bd-9c63-2391c0f7dfec.png)

so the attempt of parsing it is not a bug, but a valid behavior, just: garbage in -> garbage out.

If the size of the Import Directory was set to 0, the content won't be parsed - so, there will be no garbage imports - but the Imports tab will be displayed, because the VA of the Import Table is still non-zero:

![size_set_to_zero](https://user-images.githubusercontent.com/3115348/171176764-2b8c9430-b6ae-4ad8-98db-92f3475d4b14.png)

![empty_table](https://user-images.githubusercontent.com/3115348/171176779-5ca43eb3-86b2-49e6-ab8e-d2079c5ed914.png)

This is not a bug, but intended  behavior. The tab is shown, because the PE *do have* imports directory, even if they are invalid.

**Comment by Shadlock0133** [comment]
I was mostly surprised because the data dir is supposed to be empty. So it contains "garbage" because it read data from sections headers.

**Comment by hasherezade** [comment]
>data dir is supposed to be empty.

but in the Data Directory the Import Table is not empty - the RVA is set to `1`:

![filled](https://user-images.githubusercontent.com/3115348/171190560-902e78fa-7cda-495c-b438-9a89b3fd1c55.png)

So PE-bear reads whatever this RVA points to.
